import type { Occurrence } from '@/types'
import { cn } from '@/lib/cn'

export function OccurrenceRow({
  occ, isSelected, onClick,
}: {
  occ: Occurrence
  isSelected: boolean
  onClick: () => void
}) {
  return (
    <div
      onClick={onClick}
      className={cn(
        'flex items-center gap-2 px-3 py-2 border-b border-white/5 text-xs font-mono cursor-pointer select-none transition-colors',
        isSelected ? 'bg-blue-500/10 border-l-2 border-l-blue-500/60' : 'hover:bg-white/[0.03]',
        occ.metadata.done && 'opacity-40'
      )}
    >
      <span
        className={cn('w-1.5 h-1.5 rounded-full shrink-0', occ.source === 'generated' ? 'bg-white/30' : 'bg-amber-400/60')}
        title={occ.source === 'generated' ? 'generated by schedule' : 'explicit instance'}
      />
      <span className={cn('shrink-0 text-white/80', occ.metadata.done && 'line-through')}>{occ.date}</span>
      {occ.time
        ? <span className="text-white/40 shrink-0">{occ.time}</span>
        : <span className="text-white/15 shrink-0">—</span>}
      <span className={cn(
        'ml-auto text-2xs font-sans px-1.5 py-0.5 rounded',
        occ.source === 'generated' ? 'bg-white/5 text-white/25' : 'bg-amber-500/10 text-amber-400/70'
      )}>
        {occ.source === 'generated' ? 'sched' : 'explicit'}
      </span>
      {occ.metadata.done && (
        <span className="text-2xs px-1.5 py-0.5 rounded bg-emerald-500/15 text-emerald-400 font-sans">done</span>
      )}
    </div>
  )
}
